# -*- coding: utf-8 -*-
"""Junior_sD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nVGfM1Ujj2LkfaASFxZFFuXEPRbFhzIY
"""



from google.colab import files

uploaded = files.upload()

import pdfplumber

def extract_text_from_pdf(path):
    text = ""
    with pdfplumber.open(path) as pdf:
        for page in pdf.pages:
            page_text = page.extract_text()
            if page_text:
                text += page_text + "\n"
    return text


pdf_path = list(uploaded.keys())[0]
text = extract_text_from_pdf(pdf_path)

print(text[:2000])  # preview extracted text

import re

MANDATORY_FIELDS = [
    "policy_number",
    "policyholder_name",
    "date_of_loss",
    "description",
    "claim_type",
    "estimated_damage"
]

FIELD_PATTERNS = {
    "policy_number": r"POLICY NUMBER[:\s]+([A-Z0-9-]+)",
    "policyholder_name": r"NAME OF INSURED.*?:\s*(.+)",
    "date_of_loss": r"DATE OF LOSS[:\s]+([0-9/]+)",
    "location": r"LOCATION OF LOSS[:\s]+(.+)",
    "description": r"DESCRIPTION OF (ACCIDENT|LOSS)[:\s]+(.+)",
    "estimated_damage": r"ESTIMATE AMOUNT[:\s]+\$?([0-9,]+)",
    "claim_type": r"LINE OF BUSINESS[:\s]+(.+)"
}

def extract_fields(text):
    extracted = {}

    for field, pattern in FIELD_PATTERNS.items():
        match = re.search(pattern, text, re.IGNORECASE | re.DOTALL)
        if match:
            extracted[field] = match.group(len(match.groups())).strip()
        else:
            extracted[field] = None

    # Normalize estimated damage
    if extracted.get("estimated_damage"):
        extracted["estimated_damage"] = int(
            extracted["estimated_damage"].replace(",", "")
        )

    return extracted


extracted_fields = extract_fields(text)
extracted_fields

def find_missing_fields(extracted):
    return [
        field for field in MANDATORY_FIELDS
        if not extracted.get(field)
    ]


missing_fields = find_missing_fields(extracted_fields)
missing_fields

def route_claim(extracted, missing_fields):
    description = (extracted.get("description") or "").lower()
    estimate = extracted.get("estimated_damage", 0)
    claim_type = (extracted.get("claim_type") or "").lower()

    if missing_fields:
        return "Manual Review", "Mandatory fields are missing"

    if any(word in description for word in ["fraud", "staged", "inconsistent"]):
        return "Investigation Flag", "Suspicious keywords detected"

    if "injury" in claim_type:
        return "Specialist Queue", "Injury-related claim"

    if estimate < 25000:
        return "Fast-track", "Estimated damage below $25,000"

    return "Standard Processing", "Default routing rules applied"


route, reasoning = route_claim(extracted_fields, missing_fields)
route, reasoning

import json

output = {
    "extractedFields": extracted_fields,
    "missingFields": missing_fields,
    "recommendedRoute": route,
    "reasoning": reasoning
}

print(json.dumps(output, indent=2))

